/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl STATUSEVENTHANDLER
// ------------------------------
#ifndef STATUSEVENTHANDLER_EXPORT_H
#define STATUSEVENTHANDLER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (STATUSEVENTHANDLER_HAS_DLL)
#  define STATUSEVENTHANDLER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && STATUSEVENTHANDLER_HAS_DLL */

#if !defined (STATUSEVENTHANDLER_HAS_DLL)
#  define STATUSEVENTHANDLER_HAS_DLL 1
#endif /* ! STATUSEVENTHANDLER_HAS_DLL */

#if defined (STATUSEVENTHANDLER_HAS_DLL) && (STATUSEVENTHANDLER_HAS_DLL == 1)
#  if defined (STATUSEVENTHANDLER_BUILD_DLL)
#    define STATUSEVENTHANDLER_Export ACE_Proper_Export_Flag
#    define STATUSEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define STATUSEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* STATUSEVENTHANDLER_BUILD_DLL */
#    define STATUSEVENTHANDLER_Export ACE_Proper_Import_Flag
#    define STATUSEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define STATUSEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* STATUSEVENTHANDLER_BUILD_DLL */
#else /* STATUSEVENTHANDLER_HAS_DLL == 1 */
#  define STATUSEVENTHANDLER_Export
#  define STATUSEVENTHANDLER_SINGLETON_DECLARATION(T)
#  define STATUSEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* STATUSEVENTHANDLER_HAS_DLL == 1 */

// Set STATUSEVENTHANDLER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (STATUSEVENTHANDLER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define STATUSEVENTHANDLER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define STATUSEVENTHANDLER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !STATUSEVENTHANDLER_NTRACE */

#if (STATUSEVENTHANDLER_NTRACE == 1)
#  define STATUSEVENTHANDLER_TRACE(X)
#else /* (STATUSEVENTHANDLER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define STATUSEVENTHANDLER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (STATUSEVENTHANDLER_NTRACE == 1) */

#endif /* STATUSEVENTHANDLER_EXPORT_H */

// End of auto generated file.
