/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl WMIEVENTHANDLER
// ------------------------------
#ifndef WMIEVENTHANDLER_EXPORT_H
#define WMIEVENTHANDLER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (WMIEVENTHANDLER_HAS_DLL)
#  define WMIEVENTHANDLER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && WMIEVENTHANDLER_HAS_DLL */

#if !defined (WMIEVENTHANDLER_HAS_DLL)
#  define WMIEVENTHANDLER_HAS_DLL 1
#endif /* ! WMIEVENTHANDLER_HAS_DLL */

#if defined (WMIEVENTHANDLER_HAS_DLL) && (WMIEVENTHANDLER_HAS_DLL == 1)
#  if defined (WMIEVENTHANDLER_BUILD_DLL)
#    define WMIEVENTHANDLER_Export ACE_Proper_Export_Flag
#    define WMIEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define WMIEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* WMIEVENTHANDLER_BUILD_DLL */
#    define WMIEVENTHANDLER_Export ACE_Proper_Import_Flag
#    define WMIEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define WMIEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* WMIEVENTHANDLER_BUILD_DLL */
#else /* WMIEVENTHANDLER_HAS_DLL == 1 */
#  define WMIEVENTHANDLER_Export
#  define WMIEVENTHANDLER_SINGLETON_DECLARATION(T)
#  define WMIEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* WMIEVENTHANDLER_HAS_DLL == 1 */

// Set WMIEVENTHANDLER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (WMIEVENTHANDLER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define WMIEVENTHANDLER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define WMIEVENTHANDLER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !WMIEVENTHANDLER_NTRACE */

#if (WMIEVENTHANDLER_NTRACE == 1)
#  define WMIEVENTHANDLER_TRACE(X)
#else /* (WMIEVENTHANDLER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define WMIEVENTHANDLER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (WMIEVENTHANDLER_NTRACE == 1) */

#endif /* WMIEVENTHANDLER_EXPORT_H */

// End of auto generated file.
