/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2020 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl WATCHDOGSERVICE
// ------------------------------
#ifndef WATCHDOGSERVICE_EXPORT_H
#define WATCHDOGSERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (WATCHDOGSERVICE_HAS_DLL)
#  define WATCHDOGSERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && WATCHDOGSERVICE_HAS_DLL */

#if !defined (WATCHDOGSERVICE_HAS_DLL)
#  define WATCHDOGSERVICE_HAS_DLL 1
#endif /* ! WATCHDOGSERVICE_HAS_DLL */

#if defined (WATCHDOGSERVICE_HAS_DLL) && (WATCHDOGSERVICE_HAS_DLL == 1)
#  if defined (WATCHDOGSERVICE_BUILD_DLL)
#    define WATCHDOGSERVICE_Export ACE_Proper_Export_Flag
#    define WATCHDOGSERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define WATCHDOGSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* WATCHDOGSERVICE_BUILD_DLL */
#    define WATCHDOGSERVICE_Export ACE_Proper_Import_Flag
#    define WATCHDOGSERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define WATCHDOGSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* WATCHDOGSERVICE_BUILD_DLL */
#else /* WATCHDOGSERVICE_HAS_DLL == 1 */
#  define WATCHDOGSERVICE_Export
#  define WATCHDOGSERVICE_SINGLETON_DECLARATION(T)
#  define WATCHDOGSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* WATCHDOGSERVICE_HAS_DLL == 1 */

// Set WATCHDOGSERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (WATCHDOGSERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define WATCHDOGSERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define WATCHDOGSERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !WATCHDOGSERVICE_NTRACE */

#if (WATCHDOGSERVICE_NTRACE == 1)
#  define WATCHDOGSERVICE_TRACE(X)
#else /* (WATCHDOGSERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define WATCHDOGSERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (WATCHDOGSERVICE_NTRACE == 1) */

#endif /* WATCHDOGSERVICE_EXPORT_H */

// End of auto generated file.
