// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00717.001" type ="add">Deprecated</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ExtraCapacityGroup
// ==================================================================
   [Deprecated { "CIM_RedundancySet" }, 
    Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Core::Redundancy" ), 
    Description ( 
       "A class derived from RedundancyGroup indicating that the "
       "aggregated elements have more capacity or capability than is "
       "needed. An example of this type of redundancy is the "
       "installation of N+1 power supplies or fans in a system. \n"
       "The use of this class is being deprecated in lieu of using "
       "RedundancySet." )]
class CIM_ExtraCapacityGroup : CIM_RedundancyGroup {

      [Deprecated { "CIM_RedundancySet.MinNumberNeeded" }, 
       Description ( 
          "MinNumberNeeded indicates the smallest number of "
          "elements that must be operational in order to have "
          "redundancy. For example, in an N+1 redundancy "
          "relationship, the MinNumberNeeded property should be set "
          "equal to N." )]
   uint32 MinNumberNeeded;

      [Deprecated { "CIM_RedundancySet.TypeOfSet" }, 
       Description ( 
          "Boolean indicating whether load balancing is supported "
          "by the ExtraCapacityGroup." )]
   boolean LoadBalancedGroup;


};
