/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SHAREDSTATICIPSERVICE
// ------------------------------
#ifndef SHAREDSTATICIPSERVICE_EXPORT_H
#define SHAREDSTATICIPSERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SHAREDSTATICIPSERVICE_HAS_DLL)
#  define SHAREDSTATICIPSERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SHAREDSTATICIPSERVICE_HAS_DLL */

#if !defined (SHAREDSTATICIPSERVICE_HAS_DLL)
#  define SHAREDSTATICIPSERVICE_HAS_DLL 1
#endif /* ! SHAREDSTATICIPSERVICE_HAS_DLL */

#if defined (SHAREDSTATICIPSERVICE_HAS_DLL) && (SHAREDSTATICIPSERVICE_HAS_DLL == 1)
#  if defined (SHAREDSTATICIPSERVICE_BUILD_DLL)
#    define SHAREDSTATICIPSERVICE_Export ACE_Proper_Export_Flag
#    define SHAREDSTATICIPSERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SHAREDSTATICIPSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SHAREDSTATICIPSERVICE_BUILD_DLL */
#    define SHAREDSTATICIPSERVICE_Export ACE_Proper_Import_Flag
#    define SHAREDSTATICIPSERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SHAREDSTATICIPSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SHAREDSTATICIPSERVICE_BUILD_DLL */
#else /* SHAREDSTATICIPSERVICE_HAS_DLL == 1 */
#  define SHAREDSTATICIPSERVICE_Export
#  define SHAREDSTATICIPSERVICE_SINGLETON_DECLARATION(T)
#  define SHAREDSTATICIPSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SHAREDSTATICIPSERVICE_HAS_DLL == 1 */

// Set SHAREDSTATICIPSERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SHAREDSTATICIPSERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SHAREDSTATICIPSERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SHAREDSTATICIPSERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SHAREDSTATICIPSERVICE_NTRACE */

#if (SHAREDSTATICIPSERVICE_NTRACE == 1)
#  define SHAREDSTATICIPSERVICE_TRACE(X)
#else /* (SHAREDSTATICIPSERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SHAREDSTATICIPSERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SHAREDSTATICIPSERVICE_NTRACE == 1) */

#endif /* SHAREDSTATICIPSERVICE_EXPORT_H */

// End of auto generated file.
