/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl WINLOGEVENTHANDLER
// ------------------------------
#ifndef WINLOGEVENTHANDLER_EXPORT_H
#define WINLOGEVENTHANDLER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (WINLOGEVENTHANDLER_HAS_DLL)
#  define WINLOGEVENTHANDLER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && WINLOGEVENTHANDLER_HAS_DLL */

#if !defined (WINLOGEVENTHANDLER_HAS_DLL)
#  define WINLOGEVENTHANDLER_HAS_DLL 1
#endif /* ! WINLOGEVENTHANDLER_HAS_DLL */

#if defined (WINLOGEVENTHANDLER_HAS_DLL) && (WINLOGEVENTHANDLER_HAS_DLL == 1)
#  if defined (WINLOGEVENTHANDLER_BUILD_DLL)
#    define WINLOGEVENTHANDLER_Export ACE_Proper_Export_Flag
#    define WINLOGEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define WINLOGEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* WINLOGEVENTHANDLER_BUILD_DLL */
#    define WINLOGEVENTHANDLER_Export ACE_Proper_Import_Flag
#    define WINLOGEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define WINLOGEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* WINLOGEVENTHANDLER_BUILD_DLL */
#else /* WINLOGEVENTHANDLER_HAS_DLL == 1 */
#  define WINLOGEVENTHANDLER_Export
#  define WINLOGEVENTHANDLER_SINGLETON_DECLARATION(T)
#  define WINLOGEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* WINLOGEVENTHANDLER_HAS_DLL == 1 */

// Set WINLOGEVENTHANDLER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (WINLOGEVENTHANDLER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define WINLOGEVENTHANDLER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define WINLOGEVENTHANDLER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !WINLOGEVENTHANDLER_NTRACE */

#if (WINLOGEVENTHANDLER_NTRACE == 1)
#  define WINLOGEVENTHANDLER_TRACE(X)
#else /* (WINLOGEVENTHANDLER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define WINLOGEVENTHANDLER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (WINLOGEVENTHANDLER_NTRACE == 1) */

#endif /* WINLOGEVENTHANDLER_EXPORT_H */

// End of auto generated file.
