/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl HISTORYEVENTHANDLER
// ------------------------------
#ifndef HISTORYEVENTHANDLER_EXPORT_H
#define HISTORYEVENTHANDLER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (HISTORYEVENTHANDLER_HAS_DLL)
#  define HISTORYEVENTHANDLER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && HISTORYEVENTHANDLER_HAS_DLL */

#if !defined (HISTORYEVENTHANDLER_HAS_DLL)
#  define HISTORYEVENTHANDLER_HAS_DLL 1
#endif /* ! HISTORYEVENTHANDLER_HAS_DLL */

#if defined (HISTORYEVENTHANDLER_HAS_DLL) && (HISTORYEVENTHANDLER_HAS_DLL == 1)
#  if defined (HISTORYEVENTHANDLER_BUILD_DLL)
#    define HISTORYEVENTHANDLER_Export ACE_Proper_Export_Flag
#    define HISTORYEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define HISTORYEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* HISTORYEVENTHANDLER_BUILD_DLL */
#    define HISTORYEVENTHANDLER_Export ACE_Proper_Import_Flag
#    define HISTORYEVENTHANDLER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define HISTORYEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* HISTORYEVENTHANDLER_BUILD_DLL */
#else /* HISTORYEVENTHANDLER_HAS_DLL == 1 */
#  define HISTORYEVENTHANDLER_Export
#  define HISTORYEVENTHANDLER_SINGLETON_DECLARATION(T)
#  define HISTORYEVENTHANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* HISTORYEVENTHANDLER_HAS_DLL == 1 */

// Set HISTORYEVENTHANDLER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (HISTORYEVENTHANDLER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define HISTORYEVENTHANDLER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define HISTORYEVENTHANDLER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !HISTORYEVENTHANDLER_NTRACE */

#if (HISTORYEVENTHANDLER_NTRACE == 1)
#  define HISTORYEVENTHANDLER_TRACE(X)
#else /* (HISTORYEVENTHANDLER_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define HISTORYEVENTHANDLER_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (HISTORYEVENTHANDLER_NTRACE == 1) */

#endif /* HISTORYEVENTHANDLER_EXPORT_H */

// End of auto generated file.
