//SPDX-License-Identifier: Apache-2.0
//Copyright (C) 2009-2012 Intel Corporation

#PRAGMA AUTORECOVER
#pragma include ("s/Core/CIM_ManagedElement.mof")
#pragma include ("s/System/CIM_RecordForLog.mof")
#pragma include ("s/System/CIM_LogEntry.mof")
#pragma include ("s/User/CIM_Credential.mof")
#pragma include ("s/Core/CIM_ManagedSystemElement.mof")
#pragma include ("s/Core/CIM_LogicalElement.mof")
#pragma include ("s/Core/CIM_Job.mof")
#pragma include ("s/Core/CIM_ConcreteJob.mof")
#pragma include ("s/Core/CIM_EnabledLogicalElement.mof")
#pragma include ("s/Core/CIM_System.mof")
#pragma include ("s/System/CIM_ComputerSystem.mof")
#pragma include ("s/Core/CIM_Service.mof")
#pragma include ("s/Core/CIM_Dependency.mof")
#pragma include ("s/Core/CIM_SettingData.mof")
#pragma include ("s/Core/CIM_Component.mof")

//for implemnetation notes, internal use only
Qualifier InternalOnly : string = null,
    Scope(any),
    Flavor(EnableOverride, ToSubclass, Translatable);
#pragma include ("MEMofs/AMT_SetupAuditRecord.mof")
#pragma include ("MEMofs/AMT_ProvisioningCertificateHash.mof")
#pragma include ("MEMofs/ME_System.mof")
#pragma include ("MEMofs/OOB_Service.mof")
#pragma include ("MEMofs/AMT_Service.mof")
#pragma include ("MEmofs/AMT_EthernetPortSettings.mof")
#pragma include ("MEmofs/ME_Event.mof")
#pragma include ("MEmofs/AMT_ConcreteComponent.mof")
#pragma include ("MEmofs/AMT_HostedService.mof")
