/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl PARTIALFWUPDATESERVICE
// ------------------------------
#ifndef PARTIALFWUPDATESERVICE_EXPORT_H
#define PARTIALFWUPDATESERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (PARTIALFWUPDATESERVICE_HAS_DLL)
#  define PARTIALFWUPDATESERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && PARTIALFWUPDATESERVICE_HAS_DLL */

#if !defined (PARTIALFWUPDATESERVICE_HAS_DLL)
#  define PARTIALFWUPDATESERVICE_HAS_DLL 1
#endif /* ! PARTIALFWUPDATESERVICE_HAS_DLL */

#if defined (PARTIALFWUPDATESERVICE_HAS_DLL) && (PARTIALFWUPDATESERVICE_HAS_DLL == 1)
#  if defined (PARTIALFWUPDATESERVICE_BUILD_DLL)
#    define PARTIALFWUPDATESERVICE_Export ACE_Proper_Export_Flag
#    define PARTIALFWUPDATESERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define PARTIALFWUPDATESERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* PARTIALFWUPDATESERVICE_BUILD_DLL */
#    define PARTIALFWUPDATESERVICE_Export ACE_Proper_Import_Flag
#    define PARTIALFWUPDATESERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define PARTIALFWUPDATESERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* PARTIALFWUPDATESERVICE_BUILD_DLL */
#else /* PARTIALFWUPDATESERVICE_HAS_DLL == 1 */
#  define PARTIALFWUPDATESERVICE_Export
#  define PARTIALFWUPDATESERVICE_SINGLETON_DECLARATION(T)
#  define PARTIALFWUPDATESERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* PARTIALFWUPDATESERVICE_HAS_DLL == 1 */

// Set PARTIALFWUPDATESERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (PARTIALFWUPDATESERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define PARTIALFWUPDATESERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define PARTIALFWUPDATESERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !PARTIALFWUPDATESERVICE_NTRACE */

#if (PARTIALFWUPDATESERVICE_NTRACE == 1)
#  define PARTIALFWUPDATESERVICE_TRACE(X)
#else /* (PARTIALFWUPDATESERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define PARTIALFWUPDATESERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (PARTIALFWUPDATESERVICE_NTRACE == 1) */

#endif /* PARTIALFWUPDATESERVICE_EXPORT_H */

// End of auto generated file.
