/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2009-2019 Intel Corporation
 */
// -*- C++ -*-
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl WAITINGFORPFWLASTSERVICE
// ------------------------------
#ifndef WAITINGFORPFWLASTSERVICE_EXPORT_H
#define WAITINGFORPFWLASTSERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (WAITINGFORPFWLASTSERVICE_HAS_DLL)
#  define WAITINGFORPFWLASTSERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && WAITINGFORPFWLASTSERVICE_HAS_DLL */

#if !defined (WAITINGFORPFWLASTSERVICE_HAS_DLL)
#  define WAITINGFORPFWLASTSERVICE_HAS_DLL 1
#endif /* ! WAITINGFORPFWLASTSERVICE_HAS_DLL */

#if defined (WAITINGFORPFWLASTSERVICE_HAS_DLL) && (WAITINGFORPFWLASTSERVICE_HAS_DLL == 1)
#  if defined (WAITINGFORPFWLASTSERVICE_BUILD_DLL)
#    define WAITINGFORPFWLASTSERVICE_Export ACE_Proper_Export_Flag
#    define WAITINGFORPFWLASTSERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define WAITINGFORPFWLASTSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* WAITINGFORPFWLASTSERVICE_BUILD_DLL */
#    define WAITINGFORPFWLASTSERVICE_Export ACE_Proper_Import_Flag
#    define WAITINGFORPFWLASTSERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define WAITINGFORPFWLASTSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* WAITINGFORPFWLASTSERVICE_BUILD_DLL */
#else /* WAITINGFORPFWLASTSERVICE_HAS_DLL == 1 */
#  define WAITINGFORPFWLASTSERVICE_Export
#  define WAITINGFORPFWLASTSERVICE_SINGLETON_DECLARATION(T)
#  define WAITINGFORPFWLASTSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* WAITINGFORPFWLASTSERVICE_HAS_DLL == 1 */

// Set WAITINGFORPFWLASTSERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (WAITINGFORPFWLASTSERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define WAITINGFORPFWLASTSERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define WAITINGFORPFWLASTSERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !WAITINGFORPFWLASTSERVICE_NTRACE */

#if (WAITINGFORPFWLASTSERVICE_NTRACE == 1)
#  define WAITINGFORPFWLASTSERVICE_TRACE(X)
#else /* (WAITINGFORPFWLASTSERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define WAITINGFORPFWLASTSERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (WAITINGFORPFWLASTSERVICE_NTRACE == 1) */

#endif /* WAITINGFORPFWLASTSERVICE_EXPORT_H */

// End of auto generated file.
