/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2024 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl FWCIRAWORKAROUNDSERVICE
// ------------------------------
#ifndef FWCIRAWORKAROUNDSERVICE_EXPORT_H
#define FWCIRAWORKAROUNDSERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (FWCIRAWORKAROUNDSERVICE_HAS_DLL)
#  define FWCIRAWORKAROUNDSERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && FWCIRAWORKAROUNDSERVICE_HAS_DLL */

#if !defined (FWCIRAWORKAROUNDSERVICE_HAS_DLL)
#  define FWCIRAWORKAROUNDSERVICE_HAS_DLL 1
#endif /* ! FWCIRAWORKAROUNDSERVICE_HAS_DLL */

#if defined (FWCIRAWORKAROUNDSERVICE_HAS_DLL) && (FWCIRAWORKAROUNDSERVICE_HAS_DLL == 1)
#  if defined (FWCIRAWORKAROUNDSERVICE_BUILD_DLL)
#    define FWCIRAWORKAROUNDSERVICE_Export ACE_Proper_Export_Flag
#    define FWCIRAWORKAROUNDSERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define FWCIRAWORKAROUNDSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* FWCIRAWORKAROUNDSERVICE_BUILD_DLL */
#    define FWCIRAWORKAROUNDSERVICE_Export ACE_Proper_Import_Flag
#    define FWCIRAWORKAROUNDSERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define FWCIRAWORKAROUNDSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* FWCIRAWORKAROUNDSERVICE_BUILD_DLL */
#else /* FWCIRAWORKAROUNDSERVICE_HAS_DLL == 1 */
#  define FWCIRAWORKAROUNDSERVICE_Export
#  define FWCIRAWORKAROUNDSERVICE_SINGLETON_DECLARATION(T)
#  define FWCIRAWORKAROUNDSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* FWCIRAWORKAROUNDSERVICE_HAS_DLL == 1 */

// Set FWCIRAWORKAROUNDSERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (FWCIRAWORKAROUNDSERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define FWCIRAWORKAROUNDSERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define FWCIRAWORKAROUNDSERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !FWCIRAWORKAROUNDSERVICE_NTRACE */

#if (FWCIRAWORKAROUNDSERVICE_NTRACE == 1)
#  define FWCIRAWORKAROUNDSERVICE_TRACE(X)
#else /* (FWCIRAWORKAROUNDSERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define FWCIRAWORKAROUNDSERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (FWCIRAWORKAROUNDSERVICE_NTRACE == 1) */

#endif /* FWCIRAWORKAROUNDSERVICE_EXPORT_H */

// End of auto generated file.
