/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2013-2015 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl IPREFRESHSERVICE
// ------------------------------
#ifndef IPREFRESHSERVICE_EXPORT_H
#define IPREFRESHSERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (IPREFRESHSERVICE_HAS_DLL)
#  define IPREFRESHSERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && IPREFRESHSERVICE_HAS_DLL */

#if !defined (IPREFRESHSERVICE_HAS_DLL)
#  define IPREFRESHSERVICE_HAS_DLL 1
#endif /* ! IPREFRESHSERVICE_HAS_DLL */

#if defined (IPREFRESHSERVICE_HAS_DLL) && (IPREFRESHSERVICE_HAS_DLL == 1)
#  if defined (IPREFRESHSERVICE_BUILD_DLL)
#    define IPREFRESHSERVICE_Export ACE_Proper_Export_Flag
#    define IPREFRESHSERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define IPREFRESHSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* IPREFRESHSERVICE_BUILD_DLL */
#    define IPREFRESHSERVICE_Export ACE_Proper_Import_Flag
#    define IPREFRESHSERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define IPREFRESHSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* IPREFRESHSERVICE_BUILD_DLL */
#else /* IPREFRESHSERVICE_HAS_DLL == 1 */
#  define IPREFRESHSERVICE_Export
#  define IPREFRESHSERVICE_SINGLETON_DECLARATION(T)
#  define IPREFRESHSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* IPREFRESHSERVICE_HAS_DLL == 1 */

// Set IPREFRESHSERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (IPREFRESHSERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define IPREFRESHSERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define IPREFRESHSERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !IPREFRESHSERVICE_NTRACE */

#if (IPREFRESHSERVICE_NTRACE == 1)
#  define IPREFRESHSERVICE_TRACE(X)
#else /* (IPREFRESHSERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define IPREFRESHSERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (IPREFRESHSERVICE_NTRACE == 1) */

#endif /* IPREFRESHSERVICE_EXPORT_H */

// End of auto generated file.
