/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2018 Intel Corporation
 */
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl WIFIPROFILESYNCSERVICE
// ------------------------------
#ifndef WIFIPROFILESYNCSERVICE_EXPORT_H
#define WIFIPROFILESYNCSERVICE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (WIFIPROFILESYNCSERVICE_HAS_DLL)
#  define WIFIPROFILESYNCSERVICE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && WIFIPROFILESYNCSERVICE_HAS_DLL */

#if !defined (WIFIPROFILESYNCSERVICE_HAS_DLL)
#  define WIFIPROFILESYNCSERVICE_HAS_DLL 1
#endif /* ! WIFIPROFILESYNCSERVICE_HAS_DLL */

#if defined (WIFIPROFILESYNCSERVICE_HAS_DLL) && (WIFIPROFILESYNCSERVICE_HAS_DLL == 1)
#  if defined (WIFIPROFILESYNCSERVICE_BUILD_DLL)
#    define WIFIPROFILESYNCSERVICE_Export ACE_Proper_Export_Flag
#    define WIFIPROFILESYNCSERVICE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define WIFIPROFILESYNCSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* WIFIPROFILESYNCSERVICE_BUILD_DLL */
#    define WIFIPROFILESYNCSERVICE_Export ACE_Proper_Import_Flag
#    define WIFIPROFILESYNCSERVICE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define WIFIPROFILESYNCSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* WIFIPROFILESYNCSERVICE_BUILD_DLL */
#else /* WIFIPROFILESYNCSERVICE_HAS_DLL == 1 */
#  define WIFIPROFILESYNCSERVICE_Export
#  define WIFIPROFILESYNCSERVICE_SINGLETON_DECLARATION(T)
#  define WIFIPROFILESYNCSERVICE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* WIFIPROFILESYNCSERVICE_HAS_DLL == 1 */

// Set WIFIPROFILESYNCSERVICE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (WIFIPROFILESYNCSERVICE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define WIFIPROFILESYNCSERVICE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define WIFIPROFILESYNCSERVICE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !WIFIPROFILESYNCSERVICE_NTRACE */

#if (WIFIPROFILESYNCSERVICE_NTRACE == 1)
#  define WIFIPROFILESYNCSERVICE_TRACE(X)
#else /* (WIFIPROFILESYNCSERVICE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define WIFIPROFILESYNCSERVICE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (WIFIPROFILESYNCSERVICE_NTRACE == 1) */

#endif /* WIFIPROFILESYNCSERVICE_EXPORT_H */

// End of auto generated file.
